//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CVR { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PhonePrimary { get; set; }
        public string PhoneSecondary { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
